FROM gospew:latest
WORKDIR src/Blockchain-Framework
COPY . .
#RUN go get github.com/davecgh/go-spew/spew
RUN go build main.go
EXPOSE 8080
ENTRYPOINT [ "./main" , "-sb", "bconfig.ggs","chain"]
#ENTRYPOINT [ "./main" , "-sg"]